# Assignment 3

In [26]:
%run My_Functions_Library.ipynb  # Running the entire library in one line because 
                        # importing does not work with JupyterLab

In [27]:
# function to swap row1 and row2

def swap_rows(Ab,row1,row2):
    temp = Ab[row1]
    Ab[row1] = Ab[row2]
    Ab[row2] = temp
    return Ab


# Function for partial pivoting

def partial_pivot(Ab,m,nrows):
    pivot = Ab[m][m]    # declaring the pivot
    if (Ab[m][m] != 0):
        return Ab    # return if partial pivot is not required
    else:
        for r in range(m+1,nrows):
            # check for non-zero pivot and swap rows with it
            if Ab[r][m] != 0:
                pivot = Ab[r][m]
                Ab=swap_rows(Ab,m,r)
                return Ab
            else:
                r+=1
    if (pivot==0):    # no unique solution case
        return None


# Gauss Jordan Elimiination method

def gauss_jordan(Ab,nrows,ncols):
    det=1
    r=0
    # does partial pivoting
    Ab = partial_pivot(Ab,r,nrows)
    for r in range(0,nrows):
        # no solution case
        if Ab==None:
            return Ab
        else:
            # Changes the diagonal elements to unity
            fact=Ab[r][r]
            det=det*fact # calculates the determinant
            for c in range(r,ncols):
                Ab[r][c]*=1/fact
            # Changes the off-diagonal elements to zero
            for r1 in range(0,nrows):
                # does not change if it is already done
                if (r1==r or Ab[r1][r]==0):
                    r1+=1
                else:
                    factor = Ab[r1][r]
                    for c in range(r,ncols):
                        Ab[r1][c]-= factor * Ab[r][c]
    return Ab, det


# Function to extract inverse from augmented matrix

def get_inv(A,n):
    r=len(A)
    c=len(A[0])
    M=[[0 for j in range(n)] for i in range(n)]
    for i in range(r):
        for j in range(n,c):
            M[i][j-n]=A[i][j]
    return M


# Function to round off all elements of a matrix

def round_matrix(M,r):
    for i in range(len(M)):
        for j in range(len(M[0])):
            M[i][j]=round(M[i][j],r)
    return M


import pandas as pd   #to read csv files ONLY
import numpy as np    #to store matrices ONLY
#--------------------------------

## Question 1

In [31]:
#importing the augmented matrix 
Ab=np.array(pd.read_csv("A.csv",header=None))

#--------------------------------
nrow = lambda x: x.shape[0]
ncol = lambda x: x.shape[1]
#--------------------------------
print("The augmented matrix is: ")
print(Ab)
GJ, d=gauss_jordan(A,4,5)
if GJ!=None:
    M=round_matrix(A,2)
    print("Solutions are : ")
    for i in range(4):
        print(M[i][4])
else:
    print("No unique solution")


The augmented matrix is: 
[[ 1  1  1  1 13]
 [ 2  3  0 -1 -1]
 [-3  4  1  2 10]
 [ 1  2 -1  1  1]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()