In [11]:
from numpy import array, zeros

#a is coefficient matrix and b is constant numbers
a = array([[1,1,1,1],
          [2,3,0,-1],
          [-3,4,1,2],
          [1,2,-1,1]],float)
b = array([13,-1,10,1], float)
n = len(b)
x = zeros(n,float) #initialise or define the x or the solution vector i.e the solution vector having all 0s


### Elimination 

In [12]:
#Elimination process
for k in range(n-1):          #Fixed top row and selecting kth column
    for i in range(k+1,n):    #selecting rows below the diagonal element (k,k) as (i,k)
        if a[i,k] == 0:
            continue
        factor = a[k,k]/a[i,k]
        for j in range(k,n):
            a[i,j] = a[k,j] -a[i,j]*factor    #making all the elements below diagonal 0
        b[i] = b[k] - b[i]*factor             # the constant terms after transformation
print(a)
print(b)

[[ 1.          1.          1.          1.        ]
 [ 0.         -0.5         1.          1.5       ]
 [ 0.          0.          1.28571429  1.85714286]
 [ 0.          0.          0.          1.5       ]]
[13.  13.5 17.   7.5]


### Back-substitution

In [13]:
#Back substitution 
x[n-1] = b[n-1] / a[n-1,n-1]              #we will append from below 
for i in range(n-2,-1,-1):                #loop is descending and ends at 0 so -1, and step sixe is -1
    sum_ax = 0
    for j in range(i+1,n):
        sum_ax += a[i,j]*x[j]             #as we determine x[i] values from downward
    x[i] = (b[i] - sum_ax) / a[i,i]       #we keep them substituting for the upper rows and determine unknown x values
print('The solution of the system of linear equations are:')
print(x)


The solution of the system of linear equations are:
[ 2. -0.  6.  5.]


In [14]:
import csv


def getMatFromFile(mat_name: str):
    # opening the file to read its contents
    with open(f'{mat_name}.csv', newline='') as file:

        reader = csv.reader(file, quoting=csv.QUOTE_NONNUMERIC, delimiter=' ')

        # storing all the rows in an output list
        output = []
        for row in reader:
            output.append(row[:])

    return output


def displayMat(mat):
    if mat:
        for rows in mat:
            print([float('{:.2f}'.format(elem)) for elem in rows])
    print()


def swapRows(A, r, i, ncols):
    temp = [x for x in A[r]]
    A[r] = A[i]
    A[i] = temp


def partialPivot(A, r, nrows, ncols):
    pivot = A[r][r]
    if pivot != 0:
        return
    else:
        for i in range(r+1, nrows):
            if A[i][r] != 0:
                pivot = A[i][r]
                swapRows(A, r, i, ncols)
                break
    if pivot == 0:
        return "failed"


def guassJordan(mat, nrows, ncols):
    A = mat
    for r in range(nrows):
        x = partialPivot(A, r, nrows, ncols)
        if x == "failed":
            return "No solution exists"
        else:
            for c in range(ncols-1, r-1, -1):
                A[r][c] = A[r][c]/A[r][r]
            for row in range(nrows):
                if row != r and A[row][r] != 0:
                    factor = A[row][r]
                    for c in range(r, ncols):
                        A[row][c] -= factor*A[r][c]
    return A


def solve(mat, nrows, ncols):
    print("\nYour input system of equations in augmented matrix format is:")
    displayMat(mat)
    res = guassJordan(mat, nrows, ncols)
    print("\nYour matrix after GaussJordan Elimination is:")
    displayMat(res)
    if res == "No solution exists":
        print("No solution exists")
    else:
        print("The solutions are:")
        var_holder = {}
        for i in range(nrows):
            var_holder['x_' +
                       str(i+1)] = float('{:.2f}'.format(res[i][ncols-1]))
        locals().update(var_holder)

        for i in range(nrows):
            print(f"x_{i+1} =", vars()[f'x_{i+1}'])


def gjInverse(mat):
    print("\nYour input matrix for finding inverse is:")
    displayMat(mat)
    A = [mat[i]+[1 if i == j else 0 for j in range(len(mat))]
         for i in range(len(mat))]
    print("The augmented matrix is :")
    displayMat(A)
    A = guassJordan(A, len(mat), 2*len(mat))
    print("\nYour matrix after GaussJordan Elimination is:")
    displayMat(A)
    res = [[A[i][j] for j in range(len(A), 2*len(A))] for i in range(len(A))]
    print("Hence, the solution is:")
    displayMat(res)


def partialPivotDet(A, r, nrows, ncols):
    pivot = A[r][r]
    newSwap = 0
    if pivot != 0:
        return ("success", newSwap)
    else:
        for i in range(r+1, nrows):
            if A[i][r] != 0:
                pivot = A[i][r]
                swapRows(A, r, i, ncols)
                newSwap += 1
                return ("success", newSwap)
                break
    if pivot == 0:
        return ("failed", newSwap)


def gjDeterminant(mat, ncols):
    print("\nYour input matrix for finding determinant is:")
    displayMat(mat)
    A = mat
    swapCount = 0
    for r in range(ncols):
        x = partialPivotDet(A, r, ncols, ncols)
        swapCount += int(x[1])
        if x[0] == "failed":
            return "No solution exists"
        else:
            for row in range(r+1, ncols):
                if A[row][r] != 0:
                    factor = A[row][r]/A[r][r]
                    for c in range(r, ncols):
                        A[row][c] -= factor*A[r][c]
    k = 1
    for i in range(ncols):
        k *= A[i][i]
    return ((-1) ** swapCount)*k


mat1 = getMatFromFile("mat1")
mat2 = getMatFromFile("mat2")
mat3 = getMatFromFile("mat3")
mat4 = getMatFromFile("mat4")


print("\n######################## Answer 1 ########################")
solve(mat1, 4, 5)
print("\n######################## Answer 2 ########################")
solve(mat2, 3, 4)
print("\n######################## Answer 3 ########################")
gjInverse(mat3)
print("\n######################## Answer 4 ########################")
print("Determinant of your input matrix is: ", gjDeterminant(mat4, 4))

FileNotFoundError: [Errno 2] No such file or directory: 'mat1.csv'