### Q1-Defining matrices, storing them, finding C.D, AB, CA, and BD

In [6]:
#Defining Matrices A,B,C,D in their respective csv files and manipulating them.

import pandas as pd   #to read csv files ONLY
import numpy as np    #to store matrices ONLY
#--------------------------------
A=np.array(pd.read_csv("A.csv",header=None))
B=np.array(pd.read_csv("B.csv",header=None))
C=np.array(pd.read_csv("C.csv",header=None))
D=np.array(pd.read_csv("D.csv",header=None))
#--------------------------------
nrow = lambda x: x.shape[0]
ncol = lambda x: x.shape[1]
#--------------------------------
print(A)
def product(X,Y):
    if ncol(X)!=nrow(Y):     #to check for incompatible matrices
        raise ValueError("Error! ncol(X) doesn't match nrow(Y). Check for product compatibility.")
    else:
        XY=np.array(np.zeros((nrow(X),ncol(Y)), dtype = np.float))
        for i in range(0,nrow(X)):
            for j in range(0,nrow(Y)):
                for k in range(0,ncol(Y)):
                    XY[i,k]=XY[i,k]+X[i,j]*Y[j,k]
        return XY
def transpose(X):        #to calculate the transpose of X
    Xt=np.array(np.zeros((ncol(X),nrow(X)), dtype = np.float))
    for i in range(0,nrow(X)):
        for j in range(0,ncol(X)):
            Xt[j,i]=X[i,j]
    return Xt

print("Dot Product of C and D is:\n",product(C,transpose(D)))
print("")
print("Matrix Product of A and B is:\n",product(A,B))
print("")
print("Matrix Product of C and A is:\n",product(C,A))
print("")
print("Matrix Product of B and D is:\n",product(B,transpose(D)))


[[5 4 1]
 [2 2 6]
 [8 4 3]]
Dot Product of C and D is:
 [[45.]]

Matrix Product of A and B is:
 [[ 39.  19.  75.]
 [ 62.  36.  44.]
 [ 64.  35. 106.]]

Matrix Product of C and A is:
 [[28. 22. 35.]]

Matrix Product of B and D is:
 [[ 98.]
 [ 89.]
 [106.]]


### Q2-Class to perform complex number oprations

In [7]:
from math import atan #to define phase angle

class myComplex():

    def __init__(self, real, img, real2, img2): #class has to be defined with 4 numbers to make two complexs have real and img part
        self.r = real
        self.i = img
        self.r2 = real2
        self.i2 = img2
        
    def show(self): #to show complex numbers which are given
        print ("The complex numbers entered by you are " + str(self.r)+ " + " + str(self.i)+ "i" + " and " + str(self.r2)+ " + " + str(self.i2)+ "i")
        
        
    def add(self): #to add the two numbers
        print ("The sum is " + str(self.r + self.r2) + " + " + str(self.i +self.i2) +"i")  
        
    def product(self): #to multiply the two numbers
        print ("The product is " + str((self.r * self.r2) - (self.i * self.i2)) + " + " + str((self.i * self.r2) + (self.r * self.i2)) +"i")
        
        
    def division(self): #to divide the two numbers
        if self.r ==0 and self.i ==0 and self.r2==0 and self.i2 ==0:
            print('The division is not defined')
        else:
            print("The division of the two complex numbers are " + str(((self.r * self.r2) - (self.i * self.i2))/((self.r2)**2 - (self.i2)**2)) + " + " + str(((self.i * self.r2) + (self.r * self.i2))/((self.r2)**2 - (self.i2)**2)) +"i")

    def conjugate(self): #to get conjugate of both numbers
        print( "The conjugate of " + str(self.r)+ " + " + str(self.i)+ "i = " + str(self.r)+ " - " + str(self.i)+ "i")
        print( "The conjugate of " + str(self.r2)+ " + " + str(self.i2)+ "i = " + str(self.r2)+ " - " + str(self.i2)+ "i")

    def modulus(self): #to get mod
        print("The modulus of " + str(self.r)+ " + " + str(self.i)+ "i = " + str(((self.r)**2+(self.i)**2)**0.5))
        print("The modulus of " + str(self.r2)+ " + " + str(self.i2)+ "i = " + str(((self.r2)**2+(self.i2)**2)**0.5))

    def phase(self): #for defining phase
        if self.r ==0 and self.i ==0 and self.r2==0 and self.i2 ==0:
            print('The tan of the complex number is not defined')
        else:
            print("The phase angle of " + str(self.r)+ " + " + str(self.i)+ "i = " + str(atan(self.r/self.i)))
            print("The phase angle of " + str(self.r2)+ " + " + str(self.i2)+ "i = " + str(atan(self.r2/self.i2)))
   
 #outputs
complex = myComplex(1,2,3,4)
complex.show()
complex.add()
complex.product()
complex.division()
complex.conjugate()
complex.modulus()
complex.phase()
print()
complex = myComplex(12,14,6,8)
complex.show()
complex.add()
complex.product()
complex.division()
complex.conjugate()
complex.modulus()
complex.phase()    
print()
complex = myComplex(0,1,0,1)
complex.show()
complex.add()
complex.product()
complex.division()
complex.conjugate()
complex.modulus()
complex.phase() 
print()
complex = myComplex(0,0,0,0)
complex.show()
complex.add()
complex.product()
complex.division()
complex.conjugate()
complex.modulus()
complex.phase() 
print()
complex = myComplex(-1,2,2.5,3)
complex.show()
complex.add()
complex.product()
complex.division()
complex.conjugate()
complex.modulus()
complex.phase()        
        
        

The complex numbers entered by you are 1 + 2i and 3 + 4i
The sum is 4 + 6i
The product is -5 + 10i
The division of the two complex numbers are 0.7142857142857143 + -1.4285714285714286i
The conjugate of 1 + 2i = 1 - 2i
The conjugate of 3 + 4i = 3 - 4i
The modulus of 1 + 2i = 2.23606797749979
The modulus of 3 + 4i = 5.0
The phase angle of 1 + 2i = 0.4636476090008061
The phase angle of 3 + 4i = 0.6435011087932844

The complex numbers entered by you are 12 + 14i and 6 + 8i
The sum is 18 + 22i
The product is -40 + 180i
The division of the two complex numbers are 1.4285714285714286 + -6.428571428571429i
The conjugate of 12 + 14i = 12 - 14i
The conjugate of 6 + 8i = 6 - 8i
The modulus of 12 + 14i = 18.439088914585774
The modulus of 6 + 8i = 10.0
The phase angle of 12 + 14i = 0.7086262721276703
The phase angle of 6 + 8i = 0.6435011087932844

The complex numbers entered by you are 0 + 1i and 0 + 1i
The sum is 0 + 2i
The product is -1 + 0i
The division of the two complex numbers are 1.0 + -0.0i


### Q3- calculates average distance between any 2 points in a straight line of N equidistant points

In [8]:
def avg_dist(num_points):

    list_of_distances=[]
    sum=0 
    if num_points < 1 or num_points > 0 and num_points - int(num_points)!= 0 :
        print("The entered value is not a natural number.")
    else:
        for i in range(1,num_points+1): #chooses a point P
            for n in range(1,num_points+1): #chooses another point Q to measure distance from P
                distance= abs(i-n)
                list_of_distances.append(distance) #makes a list of distances

        for element in list_of_distances: 
            sum+=element                      #sums all the distances
        average_distance=sum/len(list_of_distances)  #divides sum by total number of point pairs considered 
        print("Average distance between two points on a straight line with",num_points,"equidistant points is ",average_distance,'units.')

avg_dist(1)
avg_dist(0)
avg_dist(-3)
avg_dist(3.2)
avg_dist(3)
avg_dist(5)


Average distance between two points on a straight line with 1 equidistant points is  0.0 units.
The entered value is not a natural number.
The entered value is not a natural number.
The entered value is not a natural number.
Average distance between two points on a straight line with 3 equidistant points is  0.8888888888888888 units.
Average distance between two points on a straight line with 5 equidistant points is  1.6 units.


### Q4- Designs a game of hangman using capital cities

In [11]:
import random #to choose randomly from a list of elements

capital_cities=[ 'Buenos Aires', 'Canberra', 'Brasilia', "Yaounde", 'Ottawa', 'Santiago', 'Beijing', 'London', 'Paris', 'Berlin', 'Rome',
'Kingston', 'Tokyo', 'Amsterdam', 'Wellington', 'Abuja', 'Oslo', 'Edinburgh', 'Pretoria', 'Bloemfontein', 'Cape Town', 'Seoul',
'Madrid', 'Stockholm', 'Bangkok', 'Washington']

def hangman(list):
    guess_made= ' '
    chosen_word=random.choice(list)
    word= chosen_word.lower()   #this prevents case sensitivity in the game
    turns= round(0.4*len(word)) #number of attempts
    name = input('Enter your name --> ')
    print('Welcome', name )
    print('-------------------')
    print("You have ",turns,"chances to guess the word, that includes spaces. So BEGIN!!")
   
    while len(word)>0:
        main_word=""    
        
        for letter in word: #creates the question
            if letter in guess_made:
                main_word=main_word + letter
            else:
                main_word=main_word +' _ '  #on first run, displays the word as _ _ _ _ 
        
        if main_word==word: #runs only when we have completely guessed the word before attempts run out
            print(main_word)
            print("You won! ",word," is the right answer.")
            break
            
        print(main_word)
        guess=input("Give a letter ")
        
        if guess.isalpha() or guess==' ':  #prevents invalid inputs like integers
            guess_made=guess_made+guess
        else:
            print("Enter a valid character")
            guess=input("Give a letter ")
        
        if guess not in word:              #code for wrong guess
            turns= turns-1   #reduces attempts by 1
            if turns==0:                  #if attempts==0, game stops
                print("You LOSE! The correct word is ",word)
                print('You let a good man die!!!')
                print('- - - - - - - - - - - - - -')
                print('             O_|            ')
                print('            /|\             ')
                print('            / \             ')
                break
            print("That's wrong! You have only ",turns," turn/turns left.") #if attempts!=0, displays warning and game goes on
            
hangman(capital_cities)  
hangman(capital_cities)
hangman(capital_cities)
hangman(capital_cities)
hangman(capital_cities)

Enter your name --> Rohan
Welcome Rohan
-------------------
You have  2 chances to guess the word, that includes spaces. So BEGIN!!
 _  _  _  _  _  _ 
Give a letter d
 _  _  _ d _  _ 
Give a letter e
That's wrong! You have only  1  turn/turns left.
 _  _  _ d _  _ 
Give a letter o
 _ o _ do _ 
Give a letter l
lo _ do _ 
Give a letter n
london
You won!  london  is the right answer.
Enter your name --> Rohan
Welcome Rohan
-------------------
You have  2 chances to guess the word, that includes spaces. So BEGIN!!
 _  _  _  _ 
Give a letter o
 _ o _  _ 
Give a letter s
That's wrong! You have only  1  turn/turns left.
 _ o _  _ 
Give a letter r
ro _  _ 
Give a letter e
ro _ e
Give a letter g
You LOSE! The correct word is  rome
You let a good man die!!!
- - - - - - - - - - - - - -
             O_|            
            /|\             
            / \             
Enter your name --> Thomas
Welcome Thomas
-------------------
You have  3 chances to guess the word, that includes spaces. So B